# Generated by Django 3.2.3 on 2021-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210606_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
